# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form, Name):
        self.log_path = "logs/" + Name + "Score.log"



        print(self.log_path)
        Form.setObjectName("Form")
        Form.resize(565, 582)
        self.listlog = QtWidgets.QTableView(Form)
        self.listlog.setGeometry(QtCore.QRect(20, 20, 521, 541))
        self.listlog.setObjectName("listlog")
        try:
            File = open(self.log_path, "r")

        except:
            print("File don't exists")
        self.settingTable()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def settingTable(self):
        # File = open()
        pass

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


from datetime import datetime

def write_log_file(device, mess, type_mess):
    now = datetime.now()
    current_time = now.strftime("%H:%M:%S %d-%m-%Y")
    file_log = open("logs/{}.log".format(device), "a+")
    line = "{0}\t{1}\t{2}\n".format(current_time, mess, type_mess)
    file_log.write(line)

def read_log_file(device):
    file_log = open("logs/{}.log".format(device), "r")